stages:
  - build
  - test
## only needed for integration test - disabled for now  
#variables:
#  DOCKER_HOST: tcp://dockerdind:2375
#  DOCKER_TLS_CERTDIR: ""

#services:
#  - name: docker:dind
#    alias: dockerdind
#    command: ["--tls=false"]

build:
  image: eclipse-temurin:21.0.10_7-jdk
  stage: build
  tags:
    - kgr1-instance-standard
## only needed for integration test - disabled for now  
#    - compose #run on gitlab runner suitable for docker
  rules:
  - if: '$CI_PIPELINE_SOURCE == "push"'
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cd backend
    - ./gradlew clean build  --exclude-task integrationTest
  artifacts:
    paths:

  artifacts:
    when: always
    paths:
      - backend/build/classes/
      - backend/build/resources/
      - backend/build/test-results/
      - backend/build/jacoco/
      - backend/build/libs/*.jar

coverage:
  image: eclipse-temurin:21.0.10_7-jdk
  stage: test
  needs:
    - job: build
      artifacts: true
  tags:
    - kgr1-instance-standard
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cd backend
    - ./gradlew jacocoTestReport --exclude-task integrationTest --no-daemon
    - ls -l
    - cat ./build/reports/jacoco/test/html/index.html
  artifacts:
    paths:
      - ./backend/build/reports/jacoco/test/*
  coverage: "/Total.*?([0-9]{1,3})%/"

#already included in build task
#npm-test:
#  image: node:latest
#  stage: test
#  variables:
#    APP_DIR: frontend
#  tags:
#    - kgr1-instance-mini
#  script:
#    - cd "$APP_DIR"
#    - npm ci
#    - npm run test-all

sast:
  stage: test
  tags:
    - kgr1-instance-mini 
include:
- template: Security/SAST.gitlab-ci.yml

#e2e:
#  stage: test
#  trigger:
#    project: kit/sfb980/legacy/component-showcase/compose-stack
#    branch: e2etesting
#    strategy: depend
#  variables:
#    SOURCEBRANCH: ${CI_COMMIT_REF_NAME}
#  allow_failure: true

docker_playground:
  stage: test
  image: docker:latest
  tags:
    - compose
  variables:
    DOCKER_HOST: tcp://dockerdind:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      alias: dockerdind
  script:
    - echo "Starting playground stack..."
    - docker compose --profile e2e up playwright
  artifacts:
    when: always
    paths:
      - playwright-docker/
