stages:
  - build
  - test
## only needed for integration test - disabled for now  
#variables:
#  DOCKER_HOST: tcp://dockerdind:2375
#  DOCKER_TLS_CERTDIR: ""

#services:
#  - name: docker:dind
#    alias: dockerdind
#    command: ["--tls=false"]

build:
  image: eclipse-temurin:17.0.9_9-jdk
  stage: build
  tags:
    - kgr1-instance-mini 
## only needed for integration test - disabled for now  
#    - compose #run on gitlab runner suitable for docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "development" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cd tuhl
    - ./gradlew clean build  --exclude-task integrationTest
  artifacts:
    paths:
      - ./tuhl/build/libs/*.jar

coverage:
  image: eclipse-temurin:17.0.9_9-jdk
  stage: test
  tags:
    - kgr1-instance-mini 
  rules:
    - if: '$CI_COMMIT_BRANCH == "development" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - cd tuhl
    - ./gradlew check jacocoTestReport --exclude-task integrationTest
    - ls -l
    - cat ./build/reports/jacoco/test/html/index.html
  artifacts:
    paths:
      - ./tuhl/build/reports/jacoco/test/*
  coverage: "/Total.*?([0-9]{1,3})%/"

sast:
  stage: test
  tags:
    - kgr1-instance-mini 
include:
- template: Security/SAST.gitlab-ci.yml

e2e:
  stage: test
  trigger:
    project: kit/sfb980/legacy/component-showcase/compose-stack
    branch: e2etesting
    strategy: depend
  variables:
    SOURCEBRANCH: ${CI_COMMIT_REF_NAME}
  allow_failure: true
#integration test is included in build anyway
#integrationtest:
#  image: eclipse-temurin:17.0.9_9-jdk
#  stage: test
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "development" && $CI_PIPELINE_SOURCE == "push"'
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" && $CI_PIPELINE_SOURCE == "merge_request_event"'
#    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"'
#  script:
#    - cd tuhl
#    - ./gradlew integrationTest