include:
  - docker-compose.minimal.yml
  - docker/compose-include-annoserver.yml
  - docker/compose-include-baserepo.yml
services:
  reverseProxy:
    image: nginx
    environment:
      - NGINXPROXY=${COMPOSE_PROXYHOST}:${COMPOSE_PROXYPORT}
    command: ["/bin/bash", "-c", "export NGINXPROXY && envsubst '$$NGINXPROXY' < /etc/nginx/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    ports:
      - "${COMPOSE_PROXYPORT}:80"
    volumes:
      - ./docker/reverseproxy/nginx.conf:/etc/nginx/default.conf.template
    depends_on:
      takita:
        condition: service_healthy
      baserepo:
        condition: service_healthy
      wapserver:
        condition: service_healthy
    networks:
      - compose-network
  sampleData:
    profiles: ["playground"]
    image: ghcr.io/orange-opensource/hurl:latest
    depends_on:
      - reverseProxy
    volumes:
      - ./tuhl/src/intTest/resources/hurl:/hurl
    entrypoint: >
      sh -c "
      hurl --variable host=http://baserepo/repo --file-root /hurl --test /hurl/repo_setup.hurl -v &&
      hurl --variable host=http://annoserver/annoserver --file-root /hurl --test /hurl/wap_setup.hurl -v &&
      curl -X POST 'http://takita:8080/actuator/searchIndex?operation=rebuild' -H 'Content-Type: application/json'
      "
    networks:
      - compose-network
  

