server {
    listen 80;
    listen [::]:80;

    server_name _;

    add_header Etag $upstream_http_etag;


    #should be working
    location /repo/ {
        proxy_pass http://baserepo/repo/;
    }

    location / {
        #http stuff on root path
        #TODO: takita has to live on root path for simplicity until it can handle context paths properly
        proxy_pass http://takita:8080;

       absolute_redirect off;

        proxy_set_header Accept-Encoding "";

        sub_filter_types *;
        sub_filter 'http://baserepo/' '$scheme://$http_host/';
        #TODO: does not seem like the greatest sub_filter
        sub_filter 'http:\/\/baserepo\/' '$scheme://$http_host/';
        sub_filter_once off;
    }

    location /annoserver/ {
        proxy_pass http://annoserver/annoserver/;
        absolute_redirect off;

        sub_filter_types *;
        #replace iris in payloads (annotations, containers, ...)
        sub_filter 'http://annoserver/' '$scheme://$http_host/';
        sub_filter_once off;

        #current workaround: nginx removes upstream etag due to sub_filter changes in payload
        add_header Etag-Upstream $upstream_http_etag;

    }

    location = /favicon.ico { access_log off; log_not_found off; }
}
