@startuml
participant Browser as b
participant "Dispatcher\nServlet" as ds

b -> ds: http post request
activate ds

ds -> ":AssistanceController" as ac : setPseudonym(pseudonym, model)
activate ac

ac -> ":IAssistanceService" as as : getUserByPseudonym(pseudonym)
activate as

as -> ":UserRepository" as ur : findOne(pseudonym)
activate ur

alt user is new
ur --> as : null


as -> ":User" as u : User(pseudonym)
activate u

u --> as : User
deactivate u

as -> ur: save(User)
activate ur

ur --> as
deactivate ur

else user already exists


ur --> as: User
deactivate ur
end
as --> ac : User
deactivate as

ac --> ds: html-file name
deactivate ac

ds --> b : http response
deactivate ds

@enduml