@startuml
participant Browser as b
participant "Dispatcher\nServlet" as ds

b -> ds: http post request
activate ds

ds -> ":FilterController" as fc: applyFilters(filterSelection, model)
activate fc

fc -> ":IFilterService" as fs: setCurrentFilters(filters)
activate fs

fs --> fc
deactivate fs

fc -> ":ISearchService" as ss: search(pageNumber)
activate ss

ss -> fs: getFilters()
activate fs

fs --> ss: currentFilters
deactivate fs

ss --> fc: searchResults for pageNumber
deactivate ss

fc --> ds: html-file name
deactivate fc

ds --> b: http response
deactivate ds
@enduml