@startuml
Browser -> "Dispatcher Servlet": http post request
activate "Dispatcher Servlet"
"Dispatcher Servlet" -> ":EditorController": addAnnotation(svg, color, motivation, model)
activate ":EditorController"
":EditorController" -> ":IEditorService": addAnnotation(svg, color)
activate ":IEditorService"
":IEditorService" -> ":IAnnotationService": addAnnotation(svg, color)
activate ":IAnnotationService"
":IAnnotationService" -> ":IAssistanceService": getCurrentPseudonym()
activate ":IAssistanceService"
":IAssistanceService"-->":IAnnotationService": pseudonym
deactivate ":IAssistanceService"
":IAnnotationService" -> ":ISearchIndexService": addAnnotation(annotation)
activate ":ISearchIndexService"
":ISearchIndexService" --> ":IAnnotationService": return
deactivate ":ISearchIndexService"
":IAnnotationService" --> ":IEditorService": return
deactivate ":IAnnotationService"
":IEditorService" -> ":EditorController": return
deactivate ":IEditorService"
":EditorController" --> "Dispatcher Servlet": html-file name
deactivate ":EditorController"
"Dispatcher Servlet" --> "Browser": http response
deactivate "Dispatcher Servlet"
@enduml