@startuml
participant Browser as b
participant "Dispatcher\nServlet" as ds

b -> ds: http post Request
activate ds

ds -> ":TableViewController" : addAttribute(attribute, model)
activate ":TableViewController"

":TableViewController" -> ":TableViewService" : addAttribute(attribute)
activate ":TableViewService"

":TableViewService" -> ":ISearchService": getResults()
activate ":ISearchService"

":ISearchService" --> ":TableViewService" : List<Manuscripts>
deactivate ":ISearchService"
":TableViewService" -> ":ISearchIndexService": get attribute specific metadata by manuscript IDs
activate ":ISearchIndexService"
":ISearchIndexService" --> ":TableViewService" : List<String>
deactivate ":ISearchIndexService"

":TableViewService" --> ":TableViewController" : HashMap<String, String>


deactivate ":TableViewService"

":TableViewController" --> ds : html-file name
deactivate ":TableViewController"

ds --> b: http Response
deactivate ds

@enduml