@startuml
"Browser" -> "Dispatcher Servlet": http post Request
activate "Dispatcher Servlet"
"Dispatcher Servlet" -> ":EditorController": selectPage(page Id, model)
activate ":EditorController"
":EditorController" -> ":IEditorService": selectPage(page Id)
activate ":IEditorService"
":IEditorService" -> ":ISearchIndexService": getPageById(page Id)
activate ":ISearchIndexService"
":ISearchIndexService" --> ":IEditorService" : page
deactivate ":ISearchIndexService"
":IEditorService" --> ":EditorController": page
deactivate ":IEditorService"
":EditorController"-->"Dispatcher Servlet": html-file name
deactivate ":EditorController"
"Dispatcher Servlet" --> "Browser": http Response
deactivate "Dispatcher Servlet"
@enduml