export {
  createDriver,
  createDrivers,
  createChromeDriver,
  createEdgeDriver,
  createFirefoxDriver,
  createSafariDriver,
  getElementById,
  getElementByXPath,
  enterPseudonym,
  leftclick,
  leftclickNode,
  rightclick,
  markWord,
  markWords,
  showAnnoCreationModal,
  chooseAnnoTemplate,
  createAnnotation,
  checkIsAnnotationCardVisible,
  getDisplayedAnnoId,
} from './utils';
