plugins {
	id 'org.springframework.boot' version '3.2.2'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'com.github.jk1.dependency-license-report' version '1.17'
	id 'java'
	id 'jacoco'
}

group = 'de.pse'
version = '0.0.3-SNAPSHOT'

repositories {
	mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
	implementation 'org.webjars:bootstrap:5.3.2'
	implementation 'org.mockito:mockito-core:5.9.0'
	implementation 'org.springframework.data:spring-data-elasticsearch'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.google.code.gson:gson:2.10.1'
	implementation 'jakarta.json:jakarta.json-api:2.1.0'
	implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
	runtimeOnly 'com.h2database:h2'
	implementation 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor "jakarta.persistence:jakarta.persistence-api:3.1.0"
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
}

test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed" //, "standardOut", "standardError"

		showExceptions true
		exceptionFormat "full"
		showCauses true
		showStackTraces true

		// Change to `true` for more verbose test output
		showStandardStreams = false
	}
}

jacocoTestReport {
	//dependsOn test // tests are required to run before generating the report
	reports {
		xml.required = true
		csv.required = true
	}
}

jar {
	manifest {
		attributes(
				'Main-Class': 'edu.kit.scc.dem.tuhl.TuhlApplication'
		)
	}
}