repository.baseUrl=http://samplerepo.edu/
repository.staticPath=api/v1/dataresources/
annotationStore.url=http://sampleannoserver.edu/wap/a04/
elasticsearch.ip=localhost
elasticsearch.port=9200
spring.datasource.url = jdbc:h2:file:~/db/mydb1
spring.jpa.hibernate.ddl-auto = update
sparqlQuery.urlPrefix = http://sampleannoserver-sparql.edu/wap/sparql?query=
devIndex.size = 5