server.port=8181
server.servlet.context-path=/takita
# episteme
#repository.baseUrl=http://samplerepo.edu/
#annotationStore.url=http://sampleannoserver.edu/wap/
#sparqlQuery.urlPrefix=http://sampleannoserver-sparql.edu/wap/sparql?query=
# metaphors
#repository.baseUrl=https://metaphors.scc.kit.edu/base-repo/
#annotationStore.url=https://metaphors.scc.kit.edu:8090/wap/
# toroll
#repository.baseUrl=https://toroll.datamanager.kit.edu/base-repo/
#annotationStore.url=https://toroll.datamanager.kit.edu:8090/wap/
# bwlcoud
#repository.baseUrl=https://276ddc12-4e43-4e64-94ba-fab7481cb713.ka.bw-cloud-instance.org/base-repo/
#annotationStore.url=https://276ddc12-4e43-4e64-94ba-fab7481cb713.ka.bw-cloud-instance.org:8090/wap/takita/
# local
repository.baseUrl=http://localhost:8090/
annotationStore.url=http://localhost:80/wap/sfb1475/
sparqlQuery.urlPrefix = http://localhost:3331/wap/sparql?query=
repository.staticPath=api/v1/dataresources/
elasticsearch.ip=127.0.0.1
elasticsearch.port=9200
spring.datasource.driver-class-name= org.h2.Driver
# springboot2
#spring.datasource.url = jdbc:h2:file:~/databaseTakita/userdb
spring.jpa.hibernate.ddl-auto = update
devIndex.size = 20
thesaurus.baseUrl = http://localhost:8091/# https://eris.vm.rub.de/Skosmos/
thesaurus.searchPath = rest/v1/ct/search
server.servlet.session.tracking-modes = COOKIE
# springboot3
spring.datasource.url = jdbc:h2:file:~/databasesTakita/databaseTakitaS3c/userdb
spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.auto_quote_keyword=true
# aai stuff
#spring.datasource.url = jdbc:h2:file:~/databasesTakita/aaiTest/userdb
#spring.security.user.name=a
#spring.security.user.password=p
# keycloak
# Endpoint where Spring Boot obtains certificates used for signature validation from. 'REALM' has to be replaced with your realm's name.
# keycloakjwt.jwk-url=http://localhost:8080/realms/takita_test_1/protocol/openid-connect/certs
# ID of the client to use 
# keycloakjwt.resource=takita_test_c_1
# JWT attribute that contains the unique username (can stay as it is)
# keycloakjwt.jwt-claim=preferred_username
# Base URL of KeyCloak
# keycloak.auth-server-url=http://localhost:8080/
# Same as keycloakjwt.resource required due to using different KeyCloak libraries. May become obsolete in future.
# keycloak.resource=takita_test_c_1
# The realm to use
# keycloak.realm =takita_test_1

# spring.security.oauth2.client.registration.keycloak.client-id=takita_test_c_1
# spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
# spring.security.oauth2.client.registration.keycloak.client-secret=add+your+long+secret+key+here+Please+replace+this+with+your+own+secret+key
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/takita_test_1
# repo.auth.jwtSecret=add+your+long+secret+key+here+Please+replace+this+with+your+own+secret+key


spring.security.oauth2.client.provider.external.issuer-uri=http://localhost:8080/realms/takita_test_1
spring.security.oauth2.client.registration.external.provider=external
spring.security.oauth2.client.registration.external.client-name=takita_test_c_1
spring.security.oauth2.client.registration.external.client-id=takita_test_c_1
spring.security.oauth2.client.registration.external.client-secret=sBnud7vH50S7rK9H5fbmyNz0KfmpGXjT
spring.security.oauth2.client.registration.external.scope=openid, offline_access, profile
spring.security.oauth2.client.registration.external.authorization-grant-type=authorization_code
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/takita_test_1
takita.security.enabled=false
takita.security.disabled=fun
ph.test=true
takita.security.success-urls=http://localhost:8181/takita/
takita.security.success-url=http://localhost:8181/takita/
takita.security.logout-url=http://localhost:8080/realms/takita_test_1/protocol/openid-connect/logout
takita.security.redirect-uri=http://localhost:8181/takita/
# exist stuff
exist.baseUrl=http://localhost:9010/exist/
exist.staticPath=rest/db/
exist.idPrefix=
exist.user.name=takita
exist.user.password=takita
logging.level.org.springframework=DEBUG
