repository.baseUrl=http://samplerepo.edu/
repository.staticPath=api/v1/dataresources/
annotationStore.url=http://sampleannoserver.edu/wap/a04/
elasticsearch.ip=localhost
elasticsearch.port=9200
spring.datasource.url = jdbc:h2:file:~/db/mydb
spring.jpa.hibernate.ddl-auto = update