#please add your remote repo
repository.baseUrl =
repository.staticPath = api/v1/dataresources/
#please add your remote anno store, usually of the form http://annostore/wap/
annotationStore.url =
#please add your sparql endpoint, usually of the form http://annostore/wap/sparql?query=
sparqlQuery.urlPrefix =
#please add your elasticsearch instance (e.g. localhost)
elasticsearch.ip =
#please add your es port (e.g. 9200)
elasticsearch.port =
spring.datasource.url = jdbc:h2:file:~/db/userdb
spring.jpa.hibernate.ddl-auto = update
devIndex.size = 5
spring.main.allow-bean-definition-overriding = true
spring.jpa.properties.hibernate.auto_quote_keyword = true

###############################################################################
# SKOSMOS settings
###############################################################################
# - feedbackLink; can be any link to redirect users when clicking on the feedback button.
#   You can use a "mailto:" link as well, to let users send an e-mail to you.
#feedbackLink =

###############################################################################
# SKOSMOS settings
###############################################################################
# - baseUrl of your SKOSMOS instance (e.g. http://localhost:9191/Skosmos)
# - searchPath of your SKOSMOS instance (e.g. rest/v1/ct/search)
#thesaurus.baseUrl =
#thesaurus.searchPath =

###############################################################################
# eXist-db settings
###############################################################################
# - baseUrl of your exist-db instance (e.g. http://localhost:9010/exist/)
# - staticPath to the REST endpoint
# - idPrefix: sometimes the xml:ids have been prefixed with a String as they start with
#   an invalid character for xml:ids. Please supply the prefix, if needed (e.g. id.)
# - name of the exist-db user
# - password of the exist-db user
#exist.baseUrl =
#exist.restEndpoint = rest/db/
#exist.idPrefix =
#exist.user.name =
#exist.user.password =

###############################################################################
# Server settings
###############################################################################
# - port (e.g. 9000). The default is "8080"
# - context path (e.g. /takita). The default is "/" (no context path)
# - tracking-modes: the session is stored in a cookie, don't change this
#server.port =
#server.servlet.context-path = /
server.servlet.session.tracking-modes = COOKIE

###############################################################################
# Monitoring settings
###############################################################################
# Settings to activate and configure hte actuator/health endpoint
# - enabled: enable/disable the health actuator (e.g. true)
# - show-details: show details of services monitored by health actuator to no one (never),
#   logged-in users (only use "when-authorized" when you have takita.security.enabled and
#   a configured keycloak instance) or to everyone (always)
# - exposure.include: expose the actuator endpoints to REST calls. List all endpoints
#   you want to expose, but it recommended to leave it at "health"
# - diskspace.enabled: enable/disable the monitoring and exposure of diskspace. Recommended
#   to leave it "false" for production environments as it shows the path to the jar file and
#   disk usage. The default is "true"
management.endpoint.health.enabled = true
management.endpoint.health.show-details = always
management.endpoints.web.exposure.include = health
management.health.diskspace.enabled = false

###############################################################################
# Security settings
###############################################################################
# Enable/disable (default) authentication. If authentication is enabled, a separate
# Authentication Service should be used in order to obtain JSON Web Tokens holding
# login information.
# - enabled (true/false). If you enable security you have to provide the respective,
# settings. Don't forget about "Security settings - Keycloak (AAI access)"
# - success-url to open when successful authentication (e.g. http://localhost:9000/takita/)
# - redirect-uri to open when a logout happened (e.g. http://localhost:9000/takita/)
takita.security.enabled = false
# takita.security.success-url =
# takita.security.redirect-uri =

###############################################################################
# Security settings - Keycloak (AAI access)
###############################################################################
# Set the values to match your keycloak instance.
# - issuer-uri: keycloak realm (e.g. http://localhost:8080/realms/takita)
# - provider don't change
# - client-name: keycloak client name (e.g. takita_client)
# - client-id: keycloak client id (most likely same as the client name; e.g. takita_client)
# - client-secret: keycloak client secret
# - scope don't change
# - authorization-grant-type don't change
#spring.security.oauth2.client.provider.external.issuer-uri =
#spring.security.oauth2.client.registration.external.provider = external
#spring.security.oauth2.client.registration.external.client-name =
#spring.security.oauth2.client.registration.external.client-id =
#spring.security.oauth2.client.registration.external.client-secret =
#spring.security.oauth2.client.registration.external.scope = openid, offline_access, profile
#spring.security.oauth2.client.registration.external.authorization-grant-type = authorization_code