#please add your remote repo
repository.baseUrl =
repository.staticPath = api/v1/dataresources/
#please add your remote anno store, usually of the form http://annostore/wap/
annotationStore.url =
#please add your sparql endpoint, usually of the form http://annostore/wap/sparql?query=
sparqlQuery.urlPrefix =
#please add your elasticsearch instance (e.g. localhost)
elasticsearch.ip =
#please add your es port (e.g. 9200)
elasticsearch.port =
spring.datasource.url = jdbc:h2:file:~/db/userdb
spring.jpa.hibernate.ddl-auto = update
devIndex.size = 5
spring.main.allow-bean-definition-overriding = true
spring.jpa.properties.hibernate.auto_quote_keyword = true