repository.baseUrl=http://repo.edu
repository.staticPath=/api/v1/dataresources/
intTest_annotationStore.baseurl=http://annoserver.edu
intTest_annotationStore.root = /wap/
annotationStore.url=http://annoserver.edu/wap/
elasticsearch.ip=localhost
elasticsearch.port=9200
#spring.datasource.url = jdbc:h2:file:~/db/userdb
spring.jpa.hibernate.ddl-auto = update
sparqlQuery.urlPrefix = http://annoserver-sparql/wap/sparql?query=
devIndex.size = 5
spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.auto_quote_keyword=true